version: 2.1
jobs:
  build:
    docker:
      - image: jgaal/devenv:bionic
    steps:
      - checkout
      - run: mkdir build
      - run:
          name: cmake 3.14.0 g++-9
          command: |
            cd build
            $CMAKE_LATEST -DCMAKE_BUILD_TYPE=Release -D CMAKE_CXX_COMPILER=/usr/bin/g++-9 -D COMPILE_TESTS=ON ..
            make -j8 && cd tests && ctest --verbose
            rm -rf *
      - run:
          name: cmake 3.14.0 g++-8
          command: |
            cd build
            $CMAKE_LATEST -DCMAKE_BUILD_TYPE=Release -D CMAKE_CXX_COMPILER=/usr/bin/g++-8 -D COMPILE_TESTS=ON ..
            make -j8 && cd tests && ctest --verbose
            rm -rf *
      - run:
          name: cmake 3.14.0 g++-7
          command: |
            cd build
            $CMAKE_LATEST -DCMAKE_BUILD_TYPE=Release -D CMAKE_CXX_COMPILER=/usr/bin/g++-7 -D COMPILE_TESTS=ON ..
            make -j8 && cd tests && ctest --verbose
            rm -rf *
      - run:
          name: cmake 3.14.0 clang++-8
          command: |
            cd build
            $CMAKE_LATEST -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=/usr/bin/clang++-8 -D COMPILE_TESTS=ON ..
            make -j8 && cd tests && ctest --verbose
            rm -rf *
      - run:
          name: cmake 3.14.0 clang++-7
          command: |
            cd build
            $CMAKE_LATEST -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=/usr/bin/clang++-7 -D COMPILE_TESTS=ON ..
            make -j8 && cd tests && ctest --verbose
            rm -rf *
