version: 2
jobs:
  build:
    docker:
      - image: ubuntu:16.04
    steps:
      - checkout
      - run: 
          name: Docker shit
          command: apt-get update -y && apt-get install -y sudo
      - run: 
          name: Run Installation script
          command: bash install.sh
